#!/usr/bin/env sh

set -ue

SCRIPT_PATH=$(cd "$(dirname "$0")" && pwd)
CMAKE_PATH=$SCRIPT_PATH/../..
BUILD_PATH=$SCRIPT_PATH/../build/make_gcc

# Run CMake.
mkdir -p "$BUILD_PATH"
cd "$BUILD_PATH"
cmake -D CMAKE_BUILD_TYPE=Release "$CMAKE_PATH"
make
