#!/usr/bin/env sh

set -ue

SCRIPT_PATH=$(cd "$(dirname "$0")" && pwd)
CMAKE_PATH=$SCRIPT_PATH/../..
BUILD_PATH=$SCRIPT_PATH/../build/proj_xcode
THIRD_PARTY_DIR=$SCRIPT_PATH/../../../thirdParty

# Run CMake.
cmake -S "$CMAKE_PATH" \
  -B "${BUILD_PATH}_iphoneos" \
  -G Xcode \
  -D CMAKE_SYSTEM_NAME=iOS \
  -D CMAKE_OSX_SYSROOT=iphoneos
